name: data-curation

channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  - python==3.10
  - ipython
  - datrie
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - mkl-service
  - Pillow
  - libjpeg-turbo
  - libpng
  - pip:
    - opencv-python
    - polars==0.16.18
    - requests
    - tqdm
    - pyarrow
    - gradio==3.50.2
    - beautifulsoup4
    - pandas
    - onnxruntime
    - onnxruntime-gpu
    - piexif
    - timm
    - chardet
